import { type AgentMessage, uuidv7 } from "@earendil-works/pi-agent-core";
import type { ImageContent, Message, TextContent, Usage } from "@earendil-works/pi-ai/compat";
import { randomUUID } from "crypto";
import {
	appendFileSync,
	closeSync,
	createReadStream,
	existsSync,
	mkdirSync,
	openSync,
	readdirSync,
	readFileSync,
	readSync,
	statSync,
	writeFileSync,
} from "fs";
import { readdir, stat } from "fs/promises";
import { join, resolve } from "path";
import { createInterface } from "readline";
import { StringDecoder } from "string_decoder";
import { getAgentDir as getDefaultAgentDir, getSessionsDir } from "../config.ts";
import { normalizePath, resolvePath } from "../utils/paths.ts";
import {
	type BashExecutionMessage,
	type CustomMessage,
	createBranchSummaryMessage,
	createCompactionSummaryMessage,
	createCustomMessage,
} from "./messages.ts";
import type { SubagentRunEntry } from "./types/subagent-entry.ts";

export const CURRENT_SESSION_VERSION = 3;

export interface SessionHeader {
	type: "session";
	version?: number; // v1 sessions don't have this
	id: string;
	timestamp: string;
	cwd: string;
	parentSession?: string;
}

export interface NewSessionOptions {
	id?: string;
	parentSession?: string;
}

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel: string;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	provider: string;
	modelId: string;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** Usage from the LLM call(s) that generated this summary, if available. */
	usage?: Usage;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromHook?: boolean;
	/**
	 * 截至此 compaction 的全部 usage 累计（含 compaction 自身 usage 及其前全部条目的
	 * usage，无论其前条目是否被 lazy 占位跳过）。footer 以最后一个带此字段的 compaction
	 * 作基线恢复 resume 后的累计用量。仅新写入的 compaction 携带，旧会话文件无此字段。
	 */
	cumulativeUsage?: Usage;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** Usage from the LLM call(s) that generated this summary, if available. */
	usage?: Usage;
	/** True if generated by an extension, false if pi-generated */
	fromHook?: boolean;
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
	type: "session_info";
	name?: string;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content is converted to a user message in buildSessionContext().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
}

/**
 * 两阶段加载的中间态：message 行只 peek 元数据（v3：无大小阈值，lazy 纯按 compaction 边界），
 * 读完后据最后 compaction offset 决策。非 message 类型行不经过此态（直接 full parse）。
 * 显式 `__pending` 标记用于在第二阶段与 full-parse 的 FileEntry 区分
 * （不靠模糊的 in/类型判定）。
 */
export interface PendingEntry {
	type: "message";
	id: string;
	parentId: string | null;
	timestamp: string;
	offset: number;
	length: number;
	readonly __pending: true;
}

/**
 * compaction 前 message 条目的内存占位。仅元数据 + 磁盘偏移；
 * 访问 .message 前必须 materialize。字段顺序依赖 type/id/parentId/timestamp
 * 在序列化时位于 message 之前（peekEntryFields regex 依赖）。
 * 注意：该类型不加入 SessionEntry union，运行时以 FileEntry 形态存在于
 * fileEntries 中，下游通过 `__lazy` 标记 + optional chaining 防御。
 */
export interface LazyEntry {
	type: "message";
	id: string;
	parentId: string | null;
	timestamp: string;
	readonly __lazy: true;
	offset: number;
	length: number;
}

/**
 * 类型守卫：检测 LazyEntry 占位（compaction 前 message 的内存占位）。
 * 全仓统一经此判定，替代 `(e as { __lazy?: boolean }).__lazy` duck-typing；
 * 守卫通过后类型收窄为 LazyEntry，可直接访问 id/offset/length。
 */
export function isLazyEntry(e: unknown): e is LazyEntry {
	return (e as { __lazy?: boolean })?.__lazy === true;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| SessionInfoEntry
	| SubagentRunEntry;

/** Raw file entry (includes header) */
export type FileEntry = SessionHeader | SessionEntry;

/**
 * 累加所有 entry 的 usage：message.usage + compaction/branch_summary.usage。
 * 遇到带 cumulativeUsage 的 compaction 时以它为基线重置（其值已含 compaction 前全部 usage，
 * 包括 resume 后被 lazy 占位跳过的历史条目）——与 computeFooterUsage 对齐，避免 resume 后
 * 触发新 compaction 时 lazy 占位条目的 usage 被漏算。appendCompaction 用它写新 compaction 的
 * cumulativeUsage；footer 侧再以最后一个带 cumulativeUsage 的 compaction 作基线恢复累计。
 */
function sumEntriesUsage(entries: readonly FileEntry[]): Usage {
	let input = 0;
	let output = 0;
	let cacheRead = 0;
	let cacheWrite = 0;
	let totalTokens = 0;
	let costInput = 0;
	let costOutput = 0;
	let costCacheRead = 0;
	let costCacheWrite = 0;
	let costTotal = 0;
	for (const entry of entries) {
		// 带 cumulativeUsage 的 compaction：以其为基线重置（其值已含 compaction 前全部 usage，
		// 包括 resume 后被 lazy 占位跳过的历史条目），不重复累加其 entry.usage。
		if (entry.type === "compaction" && entry.cumulativeUsage) {
			const cum = entry.cumulativeUsage;
			input = cum.input;
			output = cum.output;
			cacheRead = cum.cacheRead;
			cacheWrite = cum.cacheWrite;
			totalTokens = cum.totalTokens;
			costInput = cum.cost.input;
			costOutput = cum.cost.output;
			costCacheRead = cum.cost.cacheRead;
			costCacheWrite = cum.cost.cacheWrite;
			costTotal = cum.cost.total;
			continue;
		}
		let usage: Usage | undefined;
		if (entry.type === "message" && entry.message?.role === "assistant") {
			usage = entry.message.usage;
		} else if (entry.type === "message" && entry.message?.role === "toolResult") {
			usage = entry.message.usage;
		} else if ((entry.type === "compaction" || entry.type === "branch_summary") && entry.usage) {
			usage = entry.usage;
		}
		if (!usage) continue;
		input += usage.input;
		output += usage.output;
		cacheRead += usage.cacheRead;
		cacheWrite += usage.cacheWrite;
		totalTokens += usage.totalTokens;
		costInput += usage.cost.input;
		costOutput += usage.cost.output;
		costCacheRead += usage.cost.cacheRead;
		costCacheWrite += usage.cost.cacheWrite;
		costTotal += usage.cost.total;
	}
	return {
		input,
		output,
		cacheRead,
		cacheWrite,
		totalTokens,
		cost: {
			input: costInput,
			output: costOutput,
			cacheRead: costCacheRead,
			cacheWrite: costCacheWrite,
			total: costTotal,
		},
	};
}

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
	entry: SessionEntry;
	children: SessionTreeNode[];
	/** Resolved label for this entry, if any */
	label?: string;
	/** Timestamp of the latest label change for this entry, if any */
	labelTimestamp?: string;
}

export interface SessionContext {
	messages: AgentMessage[];
	/** Entry IDs aligned with messages array. null for synthetic messages. */
	entryIds: (string | null)[];
	thinkingLevel: string;
	model: { provider: string; modelId: string } | null;
}

export interface SessionInfo {
	path: string;
	id: string;
	/** Working directory where the session was started. Empty string for old sessions. */
	cwd: string;
	/** User-defined display name from session_info entries. */
	name?: string;
	/** Path to the parent session (if this session was forked). */
	parentSessionPath?: string;
	created: Date;
	modified: Date;
	/** 会话文件大小（字节）——列表展示会话体量，无需解析内容，stat 直接可得。 */
	fileSize: number;
	/** 消息数（meta 缓存准确值；meta 缺失/过期时回退头部扫描近似值）。 */
	messageCount: number;
	firstMessage: string;
}

export type ReadonlySessionManager = Pick<
	SessionManager,
	| "getCwd"
	| "getSessionDir"
	| "getSessionId"
	| "getSessionFile"
	| "getLeafId"
	| "getLeafEntry"
	| "getEntry"
	| "getLabel"
	| "getBranch"
	| "buildContextEntries"
	| "getHeader"
	| "getEntries"
	| "getTree"
	| "getSessionName"
>;

function createSessionId(): string {
	return uuidv7();
}

export function assertValidSessionId(id: string): void {
	if (!/^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$/.test(id)) {
		throw new Error(
			"Session id must be non-empty, contain only alphanumeric characters, '-', '_', and '.', and start and end with an alphanumeric character",
		);
	}
}

/** Generate a unique short ID (8 hex chars, collision-checked) */
function generateId(byId: { has(id: string): boolean }): string {
	for (let i = 0; i < 100; i++) {
		const id = randomUUID().slice(0, 8);
		if (!byId.has(id)) return id;
	}
	// Fallback to full UUID if somehow we have collisions
	return randomUUID();
}

/** Migrate v1 → v2: add id/parentId tree structure. Mutates in place. */
function migrateV1ToV2(entries: FileEntry[]): void {
	const ids = new Set<string>();
	let prevId: string | null = null;

	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 2;
			continue;
		}

		entry.id = generateId(ids);
		entry.parentId = prevId;
		prevId = entry.id;

		// Convert firstKeptEntryIndex to firstKeptEntryId for compaction
		if (entry.type === "compaction") {
			const comp = entry as CompactionEntry & { firstKeptEntryIndex?: number };
			if (typeof comp.firstKeptEntryIndex === "number") {
				const targetEntry = entries[comp.firstKeptEntryIndex];
				if (targetEntry && targetEntry.type !== "session") {
					comp.firstKeptEntryId = targetEntry.id;
				}
				delete comp.firstKeptEntryIndex;
			}
		}
	}
}

/** Migrate v2 → v3: rename hookMessage role to custom. Mutates in place. */
function migrateV2ToV3(entries: FileEntry[]): void {
	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 3;
			continue;
		}

		// Update message entries with hookMessage role
		if (entry.type === "message") {
			const msgEntry = entry as SessionMessageEntry;
			if (msgEntry.message && (msgEntry.message as { role: string }).role === "hookMessage") {
				(msgEntry.message as { role: string }).role = "custom";
			}
		}
	}
}

/**
 * Run all necessary migrations to bring entries to current version.
 * Mutates entries in place. Returns true if any migration was applied.
 */
function migrateToCurrentVersion(entries: FileEntry[]): boolean {
	const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
	const version = header?.version ?? 1;

	if (version >= CURRENT_SESSION_VERSION) return false;

	if (version < 2) migrateV1ToV2(entries);
	if (version < 3) migrateV2ToV3(entries);

	return true;
}

/** Exported for testing */
export function migrateSessionEntries(entries: FileEntry[]): void {
	migrateToCurrentVersion(entries);
}

/** Exported for compaction.test.ts */
export function parseSessionEntries(content: string): FileEntry[] {
	const entries: FileEntry[] = [];
	const lines = content.trim().split("\n");

	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			const entry = JSON.parse(line) as FileEntry;
			entries.push(entry);
		} catch {
			// Skip malformed lines
		}
	}

	return entries;
}

export function getLatestCompactionEntry(entries: SessionEntry[]): CompactionEntry | null {
	for (let i = entries.length - 1; i >= 0; i--) {
		if (entries[i].type === "compaction") {
			return entries[i] as CompactionEntry;
		}
	}
	return null;
}

/**
 * Convert a single session entry to its context messages.
 * Returns an array that may be empty for entries that don't contribute
 * to LLM context directly (e.g., thinking_level_change, subagent_run).
 */
export function sessionEntryToContextMessages(entry: SessionEntry): AgentMessage[] {
	// LazyEntry（compaction 前行占位）无 .message，不贡献上下文
	if (entry.type === "message" && entry.message) {
		const message = entry.message;
		if (
			(message.role === "user" || message.role === "assistant" || message.role === "toolResult") &&
			message.content == null
		) {
			return [{ ...message, content: [] }];
		}
		return [message];
	}
	if (entry.type === "custom_message") {
		return [
			createCustomMessage(entry.customType, entry.content ?? [], entry.display, entry.details, entry.timestamp),
		];
	}
	if (entry.type === "branch_summary" && entry.summary) {
		return [createBranchSummaryMessage(entry.summary, entry.fromId, entry.timestamp)];
	}
	if (entry.type === "compaction") {
		return [createCompactionSummaryMessage(entry.summary, entry.tokensBefore, entry.timestamp)];
	}
	return [];
}

function buildEntryIndex(entries: SessionEntry[], byId?: Map<string, SessionEntry>): Map<string, SessionEntry> {
	if (byId) return byId;
	const index = new Map<string, SessionEntry>();
	for (const entry of entries) {
		index.set(entry.id, entry);
	}
	return index;
}

function buildSessionPath(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionEntry[] {
	const index = buildEntryIndex(entries, byId);
	let leaf: SessionEntry | undefined;
	if (leafId === null) {
		return [];
	}
	if (leafId) {
		leaf = index.get(leafId);
	}
	leaf ??= entries[entries.length - 1];
	if (!leaf) {
		return [];
	}

	const path: SessionEntry[] = [];
	let current: SessionEntry | undefined = leaf;
	while (current) {
		path.push(current);
		current = current.parentId ? index.get(current.parentId) : undefined;
	}
	path.reverse();
	return path;
}

/**
 * Build the active, compaction-aware session entry list.
 *
 * This follows the current leaf path. If the path contains compaction entries,
 * the latest compaction is represented by the compaction entry itself, followed
 * by the kept entries starting at firstKeptEntryId and all entries after the
 * compaction entry. Older summarized entries are omitted.
 */
export function buildContextEntries(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionEntry[] {
	const path = buildSessionPath(entries, leafId, byId);
	let compaction: CompactionEntry | null = null;

	for (const entry of path) {
		if (entry.type === "compaction") {
			compaction = entry;
		}
	}

	if (!compaction) {
		return path;
	}

	const compactionIdx = path.findIndex((entry) => entry.id === compaction.id);
	if (compactionIdx < 0) {
		return path;
	}

	const contextEntries: SessionEntry[] = [compaction];
	let foundFirstKept = false;
	for (let i = 0; i < compactionIdx; i++) {
		const entry = path[i];
		if (entry.id === compaction.firstKeptEntryId) {
			foundFirstKept = true;
		}
		if (foundFirstKept) {
			contextEntries.push(entry);
		}
	}
	contextEntries.push(...path.slice(compactionIdx + 1));
	return contextEntries;
}

/**
 * Build the session context from entries using tree traversal.
 * If leafId is provided, walks from that entry to root.
 * Handles compaction and branch summaries along the path.
 *
 * @param materializer 可选：把 LazyEntry 占位（compaction 前 kept message）恢复为完整
 *    entry 的回调（如 `SessionManager.materialize`）。提供时，compaction 保留的
 *    kept messages 会恢复并进入 LLM 上下文；缺省时 lazy 占位被跳过（向后兼容）。
 */
export function buildSessionContext(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
	materializer?: (id: string) => SessionEntry | undefined,
): SessionContext {
	// Build uuid index if not available
	if (!byId) {
		byId = new Map<string, SessionEntry>();
		for (const entry of entries) {
			byId.set(entry.id, entry);
		}
	}

	// Find leaf
	let leaf: SessionEntry | undefined;
	if (leafId === null) {
		// Explicitly null - return no messages (navigated to before first entry)
		return { messages: [], entryIds: [], thinkingLevel: "off", model: null };
	}
	if (leafId) {
		leaf = byId.get(leafId);
	}
	if (!leaf) {
		// Fallback to last entry (when leafId is undefined)
		leaf = entries[entries.length - 1];
	}

	if (!leaf) {
		return { messages: [], entryIds: [], thinkingLevel: "off", model: null };
	}

	// Walk from leaf to root, collecting path
	// push + reverse（unshift 是 O(N)，长路径下 O(N²)）
	const path: SessionEntry[] = [];
	let current: SessionEntry | undefined = leaf;
	while (current) {
		path.push(current);
		current = current.parentId ? byId.get(current.parentId) : undefined;
	}
	path.reverse();

	// Extract settings and find compaction
	let thinkingLevel = "off";
	let model: { provider: string; modelId: string } | null = null;
	let compaction: CompactionEntry | null = null;

	for (const entry of path) {
		if (entry.type === "thinking_level_change") {
			thinkingLevel = entry.thinkingLevel;
		} else if (entry.type === "model_change") {
			model = { provider: entry.provider, modelId: entry.modelId };
		} else if (entry.type === "message" && entry.message?.role === "assistant") {
			model = { provider: entry.message.provider, modelId: entry.message.model };
		} else if (entry.type === "compaction") {
			compaction = entry;
		}
	}

	// Build messages and collect corresponding entries
	// When there's a compaction, we need to:
	// 1. Emit summary first (entry = compaction)
	// 2. Emit kept messages (from firstKeptEntryId up to compaction)
	// 3. Emit messages after compaction
	const messages: AgentMessage[] = [];
	const entryIds: (string | null)[] = [];

	const appendMessage = (entry: SessionEntry) => {
		// LazyEntry（compaction 前 kept message 占位）无 .message：有 materializer 时
		// 读回完整 entry 再 emit（kept 内容不丢失）；无 materializer 维持跳过占位。
		const resolved = isLazyEntry(entry) && materializer ? materializer(entry.id) : undefined;
		const full = resolved ?? entry;
		if (full.type === "message" && full.message) {
			messages.push(full.message);
			entryIds.push(full.id);
		} else if (full.type === "custom_message") {
			messages.push(createCustomMessage(full.customType, full.content, full.display, full.details, full.timestamp));
			entryIds.push(full.id);
		} else if (full.type === "branch_summary" && full.summary) {
			messages.push(createBranchSummaryMessage(full.summary, full.fromId, full.timestamp));
			entryIds.push(full.id);
		}
	};

	if (compaction) {
		// Emit summary first
		messages.push(createCompactionSummaryMessage(compaction.summary, compaction.tokensBefore, compaction.timestamp));
		entryIds.push(compaction.id);

		// Find compaction index in path
		const compactionIdx = path.findIndex((e) => e.type === "compaction" && e.id === compaction.id);

		// Emit kept messages (before compaction, starting from firstKeptEntryId)
		let foundFirstKept = false;
		for (let i = 0; i < compactionIdx; i++) {
			const entry = path[i];
			if (entry.id === compaction.firstKeptEntryId) {
				foundFirstKept = true;
			}
			if (foundFirstKept) {
				appendMessage(entry);
			}
		}

		// Emit messages after compaction
		for (let i = compactionIdx + 1; i < path.length; i++) {
			const entry = path[i];
			appendMessage(entry);
		}
	} else {
		// No compaction - emit all messages, handle branch summaries and custom messages
		for (const entry of path) {
			appendMessage(entry);
		}
	}

	return { messages, entryIds, thinkingLevel, model };
}

/**
 * Compute the default session directory for a cwd.
 * Encodes cwd into a safe directory name under ~/.pi/agent/sessions/.
 */
function getDefaultSessionDirPath(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const resolvedCwd = resolvePath(cwd);
	const resolvedAgentDir = resolvePath(agentDir);
	const safePath = `--${resolvedCwd.replace(/^[/\\]/, "").replace(/[/\\:]/g, "-")}--`;
	return join(resolvedAgentDir, "sessions", safePath);
}

export function getDefaultSessionDir(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const sessionDir = getDefaultSessionDirPath(cwd, agentDir);
	if (!existsSync(sessionDir)) {
		mkdirSync(sessionDir, { recursive: true });
	}
	return sessionDir;
}

const SESSION_READ_BUFFER_SIZE = 1024 * 1024;

function parseSessionEntryLine(line: string): FileEntry | null {
	if (!line.trim()) return null;
	try {
		return JSON.parse(line) as FileEntry;
	} catch {
		// Skip malformed lines
		return null;
	}
}

/** Regex peek 顶层字段（不全量 parse）。取不到返回 undefined 字段，调用方 fallback full parse。 */
export function peekEntryFields(line: string): { type?: string; id?: string; parentId?: string | null } {
	const type = line.match(/"type"\s*:\s*"([^"]+)"/)?.[1];
	const id = line.match(/"id"\s*:\s*"([^"]+)"/)?.[1];
	const pm = line.match(/"parentId"\s*:\s*(?:"([^"]+)"|null)/);
	return { type, id, parentId: pm ? (pm[1] ?? null) : undefined };
}

/** 从文件 offset 读 length 字节返回 utf8（materialize / lazy 序列化复用）。 */
export function readRawLine(filePath: string, offset: number, length: number): string {
	const fd = openSync(filePath, "r");
	try {
		const buf = Buffer.allocUnsafe(length);
		const n = readSync(fd, buf, 0, length, offset);
		return buf.subarray(0, n).toString("utf8");
	} finally {
		closeSync(fd);
	}
}

/**
 * 读取会话文件。两阶段（v3：lazy 纯按 compaction 边界，无大小阈值）：
 * 1. 流式读：每行 peek type——仅 type=message 的行 peek 元数据存 PendingEntry
 *    （不 parse body、不保留 raw，省内存）；其余行（session header / compaction /
 *    label / subagent_run / custom / thinking_level_change / model_change /
 *    branch_summary / session_info 等）full parse——它们小，且索引（labelsById）/
 *    查询（loadSubagentRunEntries / getLabel）需要完整字段。记录最后一个 compaction 行 offset。
 * 2. 据最后 compaction offset 决策：compaction 前 message 行 → LazyEntry（占位，
 *    materialize 时读回）；否则（compaction 后 / 无 compaction）→ readRawLine
 *    full parse（活跃或零回归）。
 */
export function loadEntriesFromFile(filePath: string): FileEntry[] {
	const resolvedFilePath = normalizePath(filePath);
	if (!existsSync(resolvedFilePath)) return [];

	// 第一阶段：流式读
	const slots: Array<FileEntry | PendingEntry> = [];
	let lastCompactionOffset: number | null = null;
	const fd = openSync(resolvedFilePath, "r");
	try {
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_READ_BUFFER_SIZE);
		let pending = "";
		let consumedBytes = 0; // 单一字节游标：已完整消费的字节数（含行尾 \n）

		const handleLine = (line: string): void => {
			const offset = consumedBytes;
			const byteLen = Buffer.byteLength(line, "utf8");
			consumedBytes += byteLen + 1; // +1 for \n
			if (byteLen === 0) return; // 空行：推进字节游标（保持 offset 与磁盘一致）但不解析
			// v3：每行 peek type（无大小阈值）。仅 type=message 的行 peek 元数据存
			// PendingEntry（阶段 2 据 compaction 边界决策 lazy/full）；其他类型
			// （label/subagent_run/custom/thinking_level_change/model_change/
			// branch_summary/session_info 等）full parse——它们小，且索引（labelsById）/
			// 查询（loadSubagentRunEntries/getLabel）需要完整字段，不能 lazy。
			// header(type=session)/compaction 亦 full parse（记录 compaction offset）。
			const f = peekEntryFields(line);
			if (f.type === "message") {
				if (f.id !== undefined && f.parentId !== undefined) {
					slots.push({
						type: "message",
						id: f.id,
						parentId: f.parentId,
						timestamp: line.match(/"timestamp"\s*:\s*"([^"]+)"/)?.[1] ?? "",
						offset,
						length: byteLen,
						__pending: true,
					});
					return;
				}
				// peek 失败（如 id 为数字）→ fallback full parse（零丢失）
			}
			const entry = parseSessionEntryLine(line);
			if (entry) {
				slots.push(entry);
				if (entry.type === "compaction") lastCompactionOffset = offset;
			}
		};

		while (true) {
			const bytesRead = readSync(fd, buffer, 0, buffer.length, null);
			if (bytesRead === 0) break;

			pending += decoder.write(buffer.subarray(0, bytesRead));
			let lineStart = 0;
			let newlineIndex = pending.indexOf("\n", lineStart);
			while (newlineIndex !== -1) {
				handleLine(pending.slice(lineStart, newlineIndex));
				lineStart = newlineIndex + 1;
				newlineIndex = pending.indexOf("\n", lineStart);
			}
			pending = pending.slice(lineStart);
		}

		pending += decoder.end();
		if (pending.trim()) handleLine(pending);
	} finally {
		closeSync(fd);
	}

	// 第二阶段：据 lastCompactionOffset 决策 pending
	const entries: FileEntry[] = [];
	for (const slot of slots) {
		if ((slot as PendingEntry).__pending) {
			const p = slot as PendingEntry;
			if (lastCompactionOffset !== null && p.offset < lastCompactionOffset) {
				// compaction 前行 → LazyEntry 占位
				entries.push({
					type: "message",
					id: p.id,
					parentId: p.parentId,
					timestamp: p.timestamp,
					__lazy: true,
					offset: p.offset,
					length: p.length,
				} as unknown as FileEntry);
			} else {
				// compaction 后（活跃）或无 compaction（零回归）→ full parse
				const raw = readRawLine(resolvedFilePath, p.offset, p.length);
				const full = parseSessionEntryLine(raw);
				if (full) entries.push(full);
			}
		} else {
			entries.push(slot as FileEntry);
		}
	}

	// Validate session header
	if (entries.length === 0) return entries;
	const header = entries[0];
	if (header.type !== "session" || typeof (header as { id?: unknown }).id !== "string") {
		return [];
	}

	return entries;
}

function readSessionHeader(filePath: string): SessionHeader | null {
	try {
		const fd = openSync(filePath, "r");
		const buffer = Buffer.alloc(512);
		const bytesRead = readSync(fd, buffer, 0, 512, 0);
		closeSync(fd);
		const firstLine = buffer.toString("utf8", 0, bytesRead).split("\n")[0];
		if (!firstLine) return null;
		const header = JSON.parse(firstLine) as Record<string, unknown>;
		if (header.type !== "session" || typeof header.id !== "string") {
			return null;
		}
		return header as unknown as SessionHeader;
	} catch {
		return null;
	}
}

function getSessionHeaderCwd(header: SessionHeader): string | undefined {
	const cwd = (header as { cwd?: unknown }).cwd;
	return typeof cwd === "string" ? cwd : undefined;
}

function sessionCwdMatches(cwd: string | undefined, resolvedCwd: string): boolean {
	return cwd !== undefined && cwd !== "" && resolvePath(cwd) === resolvedCwd;
}

/** Exported for testing */
export function findMostRecentSession(sessionDir: string, cwd?: string): string | null {
	const resolvedSessionDir = normalizePath(sessionDir);
	const resolvedCwd = cwd ? resolvePath(cwd) : undefined;
	try {
		const files = readdirSync(resolvedSessionDir)
			.filter((f) => f.endsWith(".jsonl"))
			.map((f) => join(resolvedSessionDir, f))
			.map((path) => ({ path, header: readSessionHeader(path) }))
			.filter(
				(file): file is { path: string; header: SessionHeader } =>
					file.header !== null &&
					(!resolvedCwd || sessionCwdMatches(getSessionHeaderCwd(file.header), resolvedCwd)),
			)
			.map(({ path }) => ({ path, mtime: statSync(path).mtime }))
			.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

		return files[0]?.path || null;
	} catch {
		return null;
	}
}

function isMessageWithContent(message: AgentMessage): message is Message {
	return typeof (message as Message).role === "string" && "content" in message;
}

function extractTextContent(message: Message): string {
	const content = message.content;
	if (typeof content === "string") {
		return content;
	}
	return content
		.filter((block): block is TextContent => block.type === "text")
		.map((block) => block.text)
		.join(" ");
}

function getMessageActivityTime(entry: SessionMessageEntry): number | undefined {
	const message = entry.message;
	if (!isMessageWithContent(message)) return undefined;
	if (message.role !== "user" && message.role !== "assistant") return undefined;

	const msgTimestamp = (message as { timestamp?: number }).timestamp;
	if (typeof msgTimestamp === "number") {
		return msgTimestamp;
	}

	const t = new Date(entry.timestamp).getTime();
	return Number.isNaN(t) ? undefined : t;
}

const MAX_SESSION_INFO_HEAD_LINES = 100;
/**
 * 伴生 meta 文件（${filePath}.meta）结构：缓存主文件的 size 与列表构建所需的
 * name/lastActivityMs，使列表构建无需扫描文件内容。
 */
interface SessionMeta {
	size: number;
	lastActivityMs?: number;
	name?: string;
	hasSessionInfo: boolean;
	/** 全文件消息数（append 时递增维护），列表展示无需扫描内容。 */
	messageCount?: number;
}

/** 读伴生 meta 文件（${filePath}.meta）。不存在/损坏/字段不合法返回 undefined。 */
function readSessionMeta(filePath: string): SessionMeta | undefined {
	const metaPath = `${filePath}.meta`;
	if (!existsSync(metaPath)) return undefined;
	try {
		const data = JSON.parse(readFileSync(metaPath, "utf8")) as {
			size?: unknown;
			lastActivityMs?: unknown;
			name?: unknown;
			hasSessionInfo?: unknown;
			messageCount?: unknown;
		};
		if (typeof data.size !== "number") return undefined;
		return {
			size: data.size,
			lastActivityMs: typeof data.lastActivityMs === "number" ? data.lastActivityMs : undefined,
			name: typeof data.name === "string" ? data.name : undefined,
			hasSessionInfo: data.hasSessionInfo === true,
			messageCount: typeof data.messageCount === "number" ? data.messageCount : undefined,
		};
	} catch {
		return undefined;
	}
}

async function buildSessionInfo(filePath: string): Promise<SessionInfo | null> {
	try {
		const stats = await stat(filePath);
		let header: SessionHeader | null = null;
		let firstMessage = "";
		let name: string | undefined;
		let headMessageCount = 0;

		// 只扫描文件头部：header + 标题（firstMessage/name）均取自此处。
		// 不读整个文件——几百 MB 会话的列表构建只开销头部 I/O。
		// messageCount 优先取 meta 缓存（准确）；头部计数仅作 meta 缺失/过期时的回退近似。
		const rl = createInterface({
			input: createReadStream(filePath, { encoding: "utf8" }),
			crlfDelay: Infinity,
		});

		let linesRead = 0;
		for await (const line of rl) {
			linesRead++;
			if (linesRead > MAX_SESSION_INFO_HEAD_LINES) break;

			const entry = parseSessionEntryLine(line);
			if (!entry) continue;

			if (!header) {
				if (entry.type !== "session") return null;
				header = entry;
				continue;
			}

			// Extract session name (use latest, including explicit clears)
			if (entry.type === "session_info") {
				name = entry.name?.trim() || undefined;
				continue;
			}

			if (entry.type !== "message") continue;
			headMessageCount++;

			const message = entry.message;
			if (!isMessageWithContent(message)) continue;
			if (message.role !== "user" && message.role !== "assistant") continue;

			const textContent = extractTextContent(message);
			if (!textContent) continue;

			if (!firstMessage && message.role === "user") {
				firstMessage = textContent;
			}
		}

		if (!header) return null;

		// meta 有效（存在且 size 与主文件一致）→ name/lastActivityMs 直接用缓存，无需内容
		// 扫描；meta 缺失/过期（外部修改、写失败）→ 回退：name 用头部扫描结果，modified
		// 回退文件 mtime（append-only 下 mtime = 最后写入时刻，接近"最后活动"）。
		// size 校验保证过期 meta 不会产生错误结果。
		const meta = readSessionMeta(filePath);
		const metaIsCurrent = meta !== undefined && meta.size === stats.size;
		if (metaIsCurrent && meta.hasSessionInfo) {
			// 空名（undefined）= 清除，与头部扫描语义一致
			name = meta.name;
		}

		const cwd = typeof header.cwd === "string" ? header.cwd : "";
		const parentSessionPath = header.parentSession;
		const modified =
			metaIsCurrent && typeof meta.lastActivityMs === "number" && meta.lastActivityMs > 0
				? new Date(meta.lastActivityMs)
				: stats.mtime;

		return {
			path: filePath,
			id: header.id,
			cwd,
			name,
			parentSessionPath,
			created: new Date(header.timestamp),
			modified,
			fileSize: stats.size,
			messageCount: metaIsCurrent && typeof meta.messageCount === "number" ? meta.messageCount : headMessageCount,
			firstMessage: firstMessage || "(no messages)",
		};
	} catch {
		return null;
	}
}

export type SessionListProgress = (loaded: number, total: number) => void;

const MAX_CONCURRENT_SESSION_INFO_LOADS = 10;

async function buildSessionInfosWithConcurrency(
	files: string[],
	onLoaded: () => void,
): Promise<(SessionInfo | null)[]> {
	const results: (SessionInfo | null)[] = new Array(files.length).fill(null);
	const inFlight = new Set<Promise<void>>();
	let nextIndex = 0;

	const startNext = (): void => {
		const index = nextIndex++;
		const file = files[index];
		if (!file) return;

		let task: Promise<void>;
		task = buildSessionInfo(file)
			.then((info) => {
				results[index] = info;
			})
			.catch(() => {
				results[index] = null;
			})
			.finally(() => {
				inFlight.delete(task);
				onLoaded();
			});
		inFlight.add(task);
	};

	while (nextIndex < files.length || inFlight.size > 0) {
		while (nextIndex < files.length && inFlight.size < MAX_CONCURRENT_SESSION_INFO_LOADS) {
			startNext();
		}
		if (inFlight.size > 0) {
			await Promise.race(inFlight);
		}
	}

	return results;
}

async function listSessionsFromDir(
	dir: string,
	onProgress?: SessionListProgress,
	progressOffset = 0,
	progressTotal?: number,
): Promise<SessionInfo[]> {
	const sessions: SessionInfo[] = [];
	if (!existsSync(dir)) {
		return sessions;
	}

	try {
		const dirEntries = await readdir(dir);
		const files = dirEntries.filter((f) => f.endsWith(".jsonl")).map((f) => join(dir, f));
		const total = progressTotal ?? files.length;

		let loaded = 0;
		const results = await buildSessionInfosWithConcurrency(files, () => {
			loaded++;
			onProgress?.(progressOffset + loaded, total);
		});
		for (const info of results) {
			if (info) {
				sessions.push(info);
			}
		}
	} catch {
		// Return empty list on error
	}

	return sessions;
}

/**
 * Manages conversation sessions as append-only trees stored in JSONL files.
 *
 * Each session entry has an id and parentId forming a tree structure. The "leaf"
 * pointer tracks the current position. Appending creates a child of the current leaf.
 * Branching moves the leaf to an earlier entry, allowing new branches without
 * modifying history.
 *
 * Use buildSessionContext() to get the resolved message list for the LLM, which
 * handles compaction summaries and follows the path from root to current leaf.
 */
export class SessionManager {
	private sessionId: string = "";
	private sessionFile: string | undefined;
	private sessionDir: string;
	private cwd: string;
	private persist: boolean;
	private flushed: boolean = false;
	private fileEntries: FileEntry[] = [];
	private byId: Map<string, SessionEntry> = new Map();
	/** 伴生 meta 的内存态：列表构建据此写 ${sessionFile}.meta，避免内容扫描。 */
	private metaName: string | undefined;
	private metaHasSessionInfo = false;
	private metaLastActivityMs: number | undefined;
	/** 全文件消息数（fileEntries 统计 + append 递增），写入 meta 供列表展示。 */
	private metaMessageCount: number | undefined;
	/** entryId → fileEntries 下标。避免 materialize 时 O(N) findIndex（大会话文件 O(N²) 热点）。 */
	private entryIndex: Map<string, number> = new Map();
	private labelsById: Map<string, string> = new Map();
	private labelTimestampsById: Map<string, string> = new Map();
	private leafId: string | null = null;

	private constructor(
		cwd: string,
		sessionDir: string,
		sessionFile: string | undefined,
		persist: boolean,
		newSessionOptions?: NewSessionOptions,
		preloadedEntries?: FileEntry[],
	) {
		this.cwd = resolvePath(cwd);
		this.sessionDir = normalizePath(sessionDir);
		this.persist = persist;
		if (persist && this.sessionDir && !existsSync(this.sessionDir)) {
			mkdirSync(this.sessionDir, { recursive: true });
		}

		if (sessionFile) {
			this.setSessionFile(sessionFile, preloadedEntries);
		} else {
			this.newSession(newSessionOptions);
		}
	}

	/** Switch to a different session file (used for resume and branching) */
	setSessionFile(sessionFile: string, preloadedEntries?: FileEntry[]): void {
		this.sessionFile = resolvePath(sessionFile);
		if (existsSync(this.sessionFile)) {
			// 复用调用方（SessionManager.open）已读出的 entries，避免大文件二次全量读取。
			this.fileEntries = preloadedEntries ?? loadEntriesFromFile(this.sessionFile);

			// If file was empty, initialize it with a valid session header. If it was
			// non-empty but did not parse as a pi session, fail without modifying it.
			if (this.fileEntries.length === 0) {
				const explicitPath = this.sessionFile;
				if (statSync(explicitPath).size > 0) {
					throw new Error(`Session file is not a valid pi session: ${explicitPath}`);
				}
				this.newSession();
				this.sessionFile = explicitPath;
				this._rewriteFile();
				this.flushed = true;
				return;
			}

			const header = this.fileEntries.find((e) => e.type === "session") as SessionHeader | undefined;
			this.sessionId = header?.id ?? createSessionId();

			if (migrateToCurrentVersion(this.fileEntries)) {
				this._rewriteFile();
			}

			this._buildIndex();
			this._initMetaState();
			this.flushed = true;
		} else {
			const explicitPath = this.sessionFile;
			this.newSession();
			this.sessionFile = explicitPath; // preserve explicit path from --session flag
		}
	}

	newSession(options?: NewSessionOptions): string | undefined {
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		this.sessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: this.sessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: options?.parentSession,
		};
		this.fileEntries = [header];
		this.byId.clear();
		this.entryIndex.clear();
		this.labelsById.clear();
		this.leafId = null;
		this.flushed = false;
		this._initMetaState();

		if (this.persist) {
			const fileTimestamp = timestamp.replace(/[:.]/g, "-");
			this.sessionFile = join(this.getSessionDir(), `${fileTimestamp}_${this.sessionId}.jsonl`);
		}
		return this.sessionFile;
	}

	private _buildIndex(): void {
		this.byId.clear();
		this.entryIndex.clear();
		this.labelsById.clear();
		this.labelTimestampsById.clear();
		this.leafId = null;
		for (let i = 0; i < this.fileEntries.length; i++) {
			const entry = this.fileEntries[i];
			this.entryIndex.set(entry.id, i);
			if (entry.type === "session") continue;
			this.byId.set(entry.id, entry);
			// subagent_run entries are detached records — they must not
			// become the session leaf, or resume will lose the conversation.
			if (entry.type !== "subagent_run") {
				this.leafId = entry.id;
			}
			if (entry.type === "label") {
				if (entry.label) {
					this.labelsById.set(entry.targetId, entry.label);
					this.labelTimestampsById.set(entry.targetId, entry.timestamp);
				} else {
					this.labelsById.delete(entry.targetId);
					this.labelTimestampsById.delete(entry.targetId);
				}
			}
		}
	}

	private _lazyRawCache(): Map<string, string> {
		const cache = new Map<string, string>();
		if (!this.sessionFile) return cache;
		for (const entry of this.fileEntries) {
			if (isLazyEntry(entry)) {
				try {
					cache.set(entry.id, readRawLine(this.sessionFile, entry.offset, entry.length));
				} catch (error) {
					// 源文件不可读（例如 createBranchedSession 的 !flushed 全量写路径：
					// lazy 已在切换前 materialize，正常不会触发）；缓存缺失时
					// _writeEntryRaw fallback JSON.stringify 占位，保证系统可用。
					// 其他 IO 故障（磁盘错误、offset 损坏）会静默降级为占位并丢失真实内容，
					// 记录告警便于排查。
					console.error(`[session] failed to read lazy entry ${entry.id} raw: ${error}`);
				}
			}
		}
		return cache;
	}

	/**
	 * 写单个条目到 fd：lazy 条目从 sessionFile offset 读 raw 原样写回并更新 offset；
	 * 非 lazy 走 JSON.stringify。返回写入后的新字节 offset。
	 */
	private _writeEntryRaw(fd: number, entry: FileEntry, newOffset: number, lazyRawCache: Map<string, string>): number {
		if (isLazyEntry(entry)) {
			const raw = lazyRawCache.get(entry.id);
			if (raw !== undefined) {
				writeFileSync(fd, `${raw}\n`);
				entry.offset = newOffset;
				return newOffset + entry.length + 1;
			}
			// 缓存缺失：写入占位（不应发生，见 _lazyRawCache 注释）
		}
		const serialized = JSON.stringify(entry);
		writeFileSync(fd, `${serialized}\n`);
		return newOffset + Buffer.byteLength(serialized, "utf8") + 1;
	}

	private _rewriteFile(): void {
		if (!this.persist || !this.sessionFile) return;
		// lazy 条目需要从源文件读 raw：必须在 "w" 截断前缓存
		const lazyRawCache = this._lazyRawCache();
		const fd = openSync(this.sessionFile, "w");
		try {
			let offset = 0;
			for (const entry of this.fileEntries) {
				offset = this._writeEntryRaw(fd, entry, offset, lazyRawCache);
			}
		} finally {
			closeSync(fd);
		}
	}

	isPersisted(): boolean {
		return this.persist;
	}

	getCwd(): string {
		return this.cwd;
	}

	getSessionDir(): string {
		return this.sessionDir;
	}

	usesDefaultSessionDir(): boolean {
		return this.sessionDir === getDefaultSessionDirPath(this.cwd);
	}

	getSessionId(): string {
		return this.sessionId;
	}

	getSessionFile(): string | undefined {
		return this.sessionFile;
	}

	/** Load all subagent_run entries from the current session. */
	loadSubagentRunEntries(): SubagentRunEntry[] {
		return this.fileEntries.filter((e): e is SubagentRunEntry => e.type === "subagent_run") as SubagentRunEntry[];
	}

	/**
	 * 将 lazy 占位条目恢复为完整 message 条目（从 sessionFile 的 offset 读回 raw）。
	 * 非 lazy 条目原样返回；未知 id 返回 undefined。
	 */
	materialize(id: string): SessionEntry | undefined {
		const entry = this.byId.get(id);
		if (!entry) return undefined;
		if (!isLazyEntry(entry)) return entry;
		if (!this.sessionFile) return entry;
		const raw = readRawLine(this.sessionFile, entry.offset, entry.length);
		const full = parseSessionEntryLine(raw);
		if (!full || full.type === "session") return entry;
		this._storeMaterializedEntry(id, full);
		return full;
	}

	/**
	 * 将已读回的完整条目写入 byId 并替换 fileEntries 中的 lazy 占位。
	 * materialize 与 _materializeLazyOnBranch 共用的唯一替换入口，保持索引语义一致。
	 */
	private _storeMaterializedEntry(id: string, full: SessionEntry): void {
		this.byId.set(id, full);
		const idx = this.entryIndex.get(id);
		if (idx !== undefined && this.fileEntries[idx] && isLazyEntry(this.fileEntries[idx])) {
			this.fileEntries[idx] = full;
		}
	}

	/** Append subagent messages as children of a SubagentRunEntry.
	 *  Each message entry's parentId points to the SubagentRunEntry,
	 *  forming an independent subtree that getBranch(leafId) won't traverse.
	 *  Does NOT update leafId. */
	appendSubagentMessages(subagentEntryId: string, messages: AgentMessage[]): void {
		for (const message of messages) {
			const entry: SessionMessageEntry = {
				type: "message",
				id: generateId(this.byId),
				parentId: subagentEntryId,
				timestamp: new Date().toISOString(),
				message: message as Message,
			};
			this.fileEntries.push(entry);
			this.entryIndex.set(entry.id, this.fileEntries.length - 1);
			this.byId.set(entry.id, entry);
			// 不更新 leafId — 子树消息不影响主链
			this._persist(entry);
		}
	}

	/** Get all messages for a subagent run by its SubagentRunEntry id.
	 *  Scans fileEntries for message entries whose parentId equals subagentEntryId,
	 *  sorts by timestamp, and returns the extracted AgentMessages. */
	getSubagentMessages(subagentEntryId: string): AgentMessage[] {
		const messages: { ts: number; msg: AgentMessage }[] = [];
		for (const entry of this.fileEntries) {
			if (
				entry.type === "message" &&
				entry.parentId === subagentEntryId &&
				!isLazyEntry(entry) // lazy 占位无 .message，跳过
			) {
				messages.push({
					ts: new Date(entry.timestamp).getTime(),
					msg: (entry as SessionMessageEntry).message,
				});
			}
		}
		messages.sort((a, b) => a.ts - b.ts);
		return messages.map((m) => m.msg);
	}

	/**
	 * 从 fileEntries 重建 meta 内存态（打开会话/新会话时调用）。
	 * 从后往前第一个 session_info 即最新（空名=清除），最后一条 user/assistant
	 * 消息时间即活动时间（lazy 占位跳过，其活动时间远早于 compaction 后的
	 * 真实消息，列表用 mtime 兜底更合理）。
	 */
	private _initMetaState(): void {
		this.metaName = undefined;
		this.metaHasSessionInfo = false;
		this.metaLastActivityMs = undefined;
		this.metaMessageCount = undefined;
		let messageCount = 0;
		for (let i = this.fileEntries.length - 1; i >= 0; i--) {
			const e = this.fileEntries[i];
			if (e.type === "message") {
				// LazyEntry 占位 type 亦为 "message"，可全量统计（不触发内容读取）
				messageCount++;
			}
			if (e.type === "session_info" && !this.metaHasSessionInfo) {
				this.metaName = e.name?.trim() || undefined;
				this.metaHasSessionInfo = true;
			} else if (e.type === "message" && !isLazyEntry(e) && this.metaLastActivityMs === undefined) {
				const t = getMessageActivityTime(e as SessionMessageEntry);
				if (typeof t === "number") this.metaLastActivityMs = t;
			}
		}
		this.metaMessageCount = messageCount;
	}

	/**
	 * 主文件落盘后更新伴生 meta（${sessionFile}.meta）。size 存主文件当前字节数，
	 * 列表构建据此判断 meta 是否过期（append/重写后不一致即回退头部扫描）。
	 * 写失败静默——过期 meta 只损失快路径，不会产生错误结果。
	 */
	/** 用一条 append 的 entry 推进 meta 内存态（不写文件）。 */
	private _applyMetaEntry(entry: SessionEntry): void {
		if (entry.type === "session_info") {
			this.metaName = entry.name?.trim() || undefined;
			this.metaHasSessionInfo = true;
		} else if (entry.type === "message") {
			this.metaMessageCount = (this.metaMessageCount ?? 0) + 1;
			if (!isLazyEntry(entry)) {
				const t = getMessageActivityTime(entry as SessionMessageEntry);
				if (typeof t === "number") this.metaLastActivityMs = t;
			}
		}
	}

	private _updateSessionMeta(entry: SessionEntry): void {
		if (!this.persist || !this.sessionFile) return;
		this._applyMetaEntry(entry);
		try {
			const meta = {
				size: statSync(this.sessionFile).size,
				lastActivityMs: this.metaLastActivityMs,
				name: this.metaName,
				hasSessionInfo: this.metaHasSessionInfo,
				messageCount: this.metaMessageCount,
			};
			writeFileSync(`${this.sessionFile}.meta`, `${JSON.stringify(meta)}\n`);
		} catch {
			// meta 写失败无害：列表构建 size 校验不匹配时回退头部扫描
		}
	}

	_persist(entry: SessionEntry): void {
		if (!this.persist || !this.sessionFile) return;

		const hasAssistant = this.fileEntries.some((e) => e.type === "message" && e.message?.role === "assistant");
		if (!hasAssistant) {
			if (this.flushed) {
				appendFileSync(this.sessionFile, `${JSON.stringify(entry)}\n`);
				this._updateSessionMeta(entry);
			} else {
				// Mark as not flushed so when assistant arrives, all entries get written
				this.flushed = false;
				// 未落盘（首条 assistant 前）的条目也推进 meta 内存态——首条 assistant
				// 全量写时 _updateSessionMeta 据此写出正确的 name/lastActivityMs
				this._applyMetaEntry(entry);
			}
			return;
		}

		if (!this.flushed) {
			// 首次 assistant 到达：全量写 fileEntries（含可能的 lazy 条目，须 raw 原样写回）
			const lazyRawCache = this._lazyRawCache();
			const fd = openSync(this.sessionFile, "wx");
			try {
				let offset = 0;
				for (const e of this.fileEntries) {
					offset = this._writeEntryRaw(fd, e, offset, lazyRawCache);
				}
			} finally {
				closeSync(fd);
			}
			this.flushed = true;
			this._updateSessionMeta(entry);
		} else {
			appendFileSync(this.sessionFile, `${JSON.stringify(entry)}\n`);
			this._updateSessionMeta(entry);
		}
	}

	private _appendEntry(entry: SessionEntry): void {
		this.fileEntries.push(entry);
		this.entryIndex.set(entry.id, this.fileEntries.length - 1);
		this.byId.set(entry.id, entry);
		this.leafId = entry.id;
		this._persist(entry);
	}

	/** Append a message as child of current leaf, then advance leaf. Returns entry id.
	 * Does not allow writing CompactionSummaryMessage and BranchSummaryMessage directly.
	 * Reason: we want these to be top-level entries in the session, not message session entries,
	 * so it is easier to find them.
	 * These need to be appended via appendCompaction() and appendBranchSummary() methods.
	 */
	appendMessage(message: Message | CustomMessage | BashExecutionMessage): string {
		const entry: SessionMessageEntry = {
			type: "message",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			message,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a thinking level change as child of current leaf, then advance leaf. Returns entry id. */
	appendThinkingLevelChange(thinkingLevel: string): string {
		const entry: ThinkingLevelChangeEntry = {
			type: "thinking_level_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			thinkingLevel,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a model change as child of current leaf, then advance leaf. Returns entry id. */
	appendModelChange(provider: string, modelId: string): string {
		const entry: ModelChangeEntry = {
			type: "model_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			provider,
			modelId,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a compaction summary as child of current leaf, then advance leaf. Returns entry id. */
	appendCompaction<T = unknown>(
		summary: string,
		firstKeptEntryId: string,
		tokensBefore: number,
		details?: T,
		fromHook?: boolean,
		usage?: Usage,
	): string {
		const entry: CompactionEntry<T> = {
			type: "compaction",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			summary,
			firstKeptEntryId,
			tokensBefore,
			details,
			usage,
			fromHook,
		};
		// 必须在 _appendEntry（触发 _persist 写盘）前写入，保证 cumulativeUsage 随行持久化。
		entry.cumulativeUsage = sumEntriesUsage([...this.fileEntries, entry]);
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a custom entry (for extensions) as child of current leaf, then advance leaf. Returns entry id. */
	appendCustomEntry(customType: string, data?: unknown): string {
		const entry: CustomEntry = {
			type: "custom",
			customType,
			data,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a session info entry (e.g., display name). Returns entry id. */
	appendSessionInfo(name: string): string {
		const sanitizedName = name.replace(/[\r\n]+/g, " ").trim();
		const entry: SessionInfoEntry = {
			type: "session_info",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			name: sanitizedName,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a subagent_run reference entry. Returns entry id.
	 *  Does NOT advance leafId — subagent_run is a detached record
	 *  that should not affect the main conversation chain. */
	appendSubagentRunEntry(entry: {
		runId: string;
		index: number;
		agent: string;
		task: string;
		title?: string;
		status: "success" | "failed" | "aborted";
		model?: string;
		thinking?: string;
		totalTokens?: number;
		toolCount: number;
		outputSummary?: string;
		error?: string;
	}): string {
		const previousLeafId = this.leafId;
		const subagentEntry: SubagentRunEntry = {
			type: "subagent_run",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			...entry,
		};
		// Use _appendEntry but then restore leafId — subagent_run must not
		// become the session leaf, or resume will lose the conversation.
		this._appendEntry(subagentEntry);
		this.leafId = previousLeafId;
		return subagentEntry.id;
	}

	/** Get the current session name from the latest session_info entry, if any. */
	getSessionName(): string | undefined {
		// Walk entries in reverse to find the latest session_info entry.
		// Empty names explicitly clear the session title.
		const entries = this.getEntries();
		for (let i = entries.length - 1; i >= 0; i--) {
			const entry = entries[i];
			if (entry.type === "session_info") {
				return entry.name?.trim() || undefined;
			}
		}
		return undefined;
	}

	/**
	 * Append a custom message entry (for extensions) that participates in LLM context.
	 * @param customType Extension identifier for filtering on reload
	 * @param content Message content (string or TextContent/ImageContent array)
	 * @param display Whether to show in TUI (true = styled display, false = hidden)
	 * @param details Optional extension-specific metadata (not sent to LLM)
	 * @returns Entry id
	 */
	appendCustomMessageEntry<T = unknown>(
		customType: string,
		content: string | (TextContent | ImageContent)[],
		display: boolean,
		details?: T,
	): string {
		const entry: CustomMessageEntry<T> = {
			type: "custom_message",
			customType,
			content,
			display,
			details,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	// =========================================================================
	// Tree Traversal
	// =========================================================================

	getLeafId(): string | null {
		return this.leafId;
	}

	getLeafEntry(): SessionEntry | undefined {
		return this.leafId ? this.byId.get(this.leafId) : undefined;
	}

	getEntry(id: string): SessionEntry | undefined {
		return this.byId.get(id);
	}

	/**
	 * Get all direct children of an entry.
	 */
	getChildren(parentId: string): SessionEntry[] {
		const children: SessionEntry[] = [];
		for (const entry of this.byId.values()) {
			if (entry.parentId === parentId) {
				children.push(entry);
			}
		}
		return children;
	}

	/**
	 * Get the label for an entry, if any.
	 */
	getLabel(id: string): string | undefined {
		return this.labelsById.get(id);
	}

	/**
	 * Set or clear a label on an entry.
	 * Labels are user-defined markers for bookmarking/navigation.
	 * Pass undefined or empty string to clear the label.
	 */
	appendLabelChange(targetId: string, label: string | undefined): string {
		if (!this.byId.has(targetId)) {
			throw new Error(`Entry ${targetId} not found`);
		}
		const entry: LabelEntry = {
			type: "label",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			targetId,
			label,
		};
		this._appendEntry(entry);
		if (label) {
			this.labelsById.set(targetId, label);
			this.labelTimestampsById.set(targetId, entry.timestamp);
		} else {
			this.labelsById.delete(targetId);
			this.labelTimestampsById.delete(targetId);
		}
		return entry.id;
	}

	/**
	 * Walk from entry to root, returning all entries in path order.
	 * Includes all entry types (messages, compaction, model changes, etc.).
	 * Use buildSessionContext() to get the resolved messages for the LLM.
	 */
	getBranch(fromId?: string): SessionEntry[] {
		const path: SessionEntry[] = [];
		const startId = fromId ?? this.leafId;
		let current = startId ? this.byId.get(startId) : undefined;
		while (current) {
			path.push(current);
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
		path.reverse();
		return path;
	}

	/**
	 * Find the most recent git_snapshot custom entry at or before the given entry ID.
	 * Walks from the given entry towards root.
	 * @returns The entry data and ID if found, null otherwise
	 */
	findGitSnapshot(fromEntryId?: string | null): { data: unknown; entryId: string } | null {
		const startId = fromEntryId ?? this.leafId;
		let current = startId ? this.byId.get(startId) : undefined;
		while (current) {
			if (current.type === "custom" && (current as CustomEntry).customType === "git_snapshot") {
				return { data: (current as CustomEntry).data, entryId: current.id };
			}
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
		return null;
	}

	/**
	 * Build the active, compaction-aware session entry list for the current leaf.
	 */
	buildContextEntries(): SessionEntry[] {
		return buildContextEntries(this.getEntries(), this.leafId, this.byId);
	}

	/**
	 * Build the session context (what gets sent to the LLM).
	 * Uses tree traversal from current leaf.
	 * compaction 保留的 kept messages 以 LazyEntry 占位存在时，经 materializer 恢复后进入上下文。
	 */
	buildSessionContext(): SessionContext {
		// 一次性 materialize 主链上全部 lazy 占位（单 fd 批量读回），避免逐条
		// open/read/close 的 O(N) fd 系统调用——几百 MB 会话文件下是 resume 主要瓶颈。
		this._materializeLazyOnBranch();
		return buildSessionContext(this.getEntries(), this.leafId, this.byId);
	}

	/**
	 * 将当前分支（leaf → root 路径）上的全部 lazy 占位批量读回为完整条目。
	 * 与逐条 materialize 相比只 open 一次 fd；按 offset 排序后分段合并读（gap 小的
	 * 条目共段），减少 readSync 系统调用，段长上限 1MB 控制内存峰值。
	 * byId/fileEntries 就地替换（与 materialize 语义一致）；读回失败保持占位。
	 * 注意：路径按 leafId 解析，与 buildSessionContext 的 leaf fallback 不同——
	 * 这里 leafId 悬空时不做 entries[last] 回退（SessionManager.leafId 内部维护，
	 * 正常流程不会悬空），悬空时不 materialize 任何条目，保持占位。
	 */
	private _materializeLazyOnBranch(): void {
		if (!this.sessionFile) return;
		const lazy: LazyEntry[] = [];
		let current = this.leafId ? this.byId.get(this.leafId) : undefined;
		while (current) {
			if (isLazyEntry(current)) lazy.push(current);
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
		if (lazy.length === 0) return;
		lazy.sort((a, b) => a.offset - b.offset);

		// 分段合并：gap ≤ 64KB 且段长 ≤ 1MB 的相邻条目共段，一次 read 读整段再切片。
		const MAX_GAP = 64 * 1024;
		const MAX_CHUNK = 1024 * 1024;
		const chunks: { start: number; end: number; items: LazyEntry[] }[] = [];
		let chunk: { start: number; end: number; items: LazyEntry[] } | null = null;
		for (const l of lazy) {
			const end = l.offset + l.length;
			if (chunk && l.offset - chunk.end <= MAX_GAP && end - chunk.start <= MAX_CHUNK) {
				chunk.end = end;
				chunk.items.push(l);
			} else {
				chunk = { start: l.offset, end, items: [l] };
				chunks.push(chunk);
			}
		}

		const fd = openSync(this.sessionFile, "r");
		try {
			for (const c of chunks) {
				const buf = Buffer.allocUnsafe(c.end - c.start);
				const n = readSync(fd, buf, 0, buf.length, c.start);
				const avail = c.start + n; // 文件截断时仅处理截断点前的条目
				for (const l of c.items) {
					if (l.offset + l.length > avail) continue;
					const rel = l.offset - c.start;
					const full = parseSessionEntryLine(buf.subarray(rel, rel + l.length).toString("utf8"));
					if (!full || full.type === "session") continue;
					this._storeMaterializedEntry(l.id, full);
				}
			}
		} finally {
			closeSync(fd);
		}
	}

	/**
	 * Get session header.
	 */
	getHeader(): SessionHeader | null {
		const h = this.fileEntries.find((e) => e.type === "session");
		return h ? (h as SessionHeader) : null;
	}

	/**
	 * Get all session entries (excludes header). Returns a shallow copy.
	 * The session is append-only: use appendXXX() to add entries, branch() to
	 * change the leaf pointer. Entries cannot be modified or deleted.
	 */
	getEntries(): SessionEntry[] {
		return this.fileEntries.filter((e): e is SessionEntry => e.type !== "session");
	}

	/**
	 * Get the session as a tree structure. Returns a shallow defensive copy of all entries.
	 * A well-formed session has exactly one root (first entry with parentId === null).
	 * Orphaned entries (broken parent chain) are also returned as roots.
	 */
	getTree(): SessionTreeNode[] {
		const entries = this.getEntries();
		const nodeMap = new Map<string, SessionTreeNode>();
		const roots: SessionTreeNode[] = [];

		// Create nodes with resolved labels
		for (const entry of entries) {
			const label = this.labelsById.get(entry.id);
			const labelTimestamp = this.labelTimestampsById.get(entry.id);
			nodeMap.set(entry.id, { entry, children: [], label, labelTimestamp });
		}

		// Build tree
		for (const entry of entries) {
			const node = nodeMap.get(entry.id)!;
			if (entry.parentId === null || entry.parentId === entry.id) {
				roots.push(node);
			} else {
				const parent = nodeMap.get(entry.parentId);
				if (parent) {
					parent.children.push(node);
				} else {
					// Orphan - treat as root
					roots.push(node);
				}
			}
		}

		// Sort children by timestamp (oldest first, newest at bottom)
		// Use iterative approach to avoid stack overflow on deep trees
		const stack: SessionTreeNode[] = [...roots];
		while (stack.length > 0) {
			const node = stack.pop()!;
			node.children.sort((a, b) => new Date(a.entry.timestamp).getTime() - new Date(b.entry.timestamp).getTime());
			stack.push(...node.children);
		}

		return roots;
	}

	// =========================================================================
	// Branching
	// =========================================================================

	/**
	 * Start a new branch from an earlier entry.
	 * Moves the leaf pointer to the specified entry. The next appendXXX() call
	 * will create a child of that entry, forming a new branch. Existing entries
	 * are not modified or deleted.
	 */
	branch(branchFromId: string): void {
		if (!this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
	}

	/**
	 * Reset the leaf pointer to null (before any entries).
	 * The next appendXXX() call will create a new root entry (parentId = null).
	 * Use this when navigating to re-edit the first user message.
	 */
	resetLeaf(): void {
		this.leafId = null;
	}

	/**
	 * Start a new branch with a summary of the abandoned path.
	 * Same as branch(), but also appends a branch_summary entry that captures
	 * context from the abandoned conversation path.
	 */
	branchWithSummary(
		branchFromId: string | null,
		summary: string,
		details?: unknown,
		fromHook?: boolean,
		usage?: Usage,
	): string {
		if (branchFromId !== null && !this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
		const entry: BranchSummaryEntry = {
			type: "branch_summary",
			id: generateId(this.byId),
			parentId: branchFromId,
			timestamp: new Date().toISOString(),
			fromId: branchFromId ?? "root",
			summary,
			details,
			usage,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/**
	 * Remove all entries that are not reachable from root through the given leaf ID.
	 * Also removes orphaned labels whose targetId is no longer in the session.
	 * This is a destructive operation: orphaned entries are permanently deleted.
	 *
	 * Subagent trees (subagent_run entries and their children) are preserved
	 * regardless of their position in the main conversation tree.
	 *
	 * Returns the set of removed entry IDs (useful for cleaning up associated git refs).
	 */
	pruneOrphanedEntries(keepLeafId: string | null): Set<string> {
		const keepIds = new Set<string>();

		// Collect path from root to keepLeafId
		if (keepLeafId !== null) {
			const path = this.getBranch(keepLeafId);
			for (const entry of path) {
				keepIds.add(entry.id);
			}
		}

		// Also preserve subagent_run entries
		const subagentRunIds = new Set<string>();
		for (const entry of this.fileEntries) {
			if (entry.type === "session") continue;
			if (entry.type === "subagent_run") {
				keepIds.add(entry.id);
				subagentRunIds.add(entry.id);
			}
		}

		// Transitive closure: add entries whose parent chain traces back to a subagent_run.
		// Only traverse into the subagent subtrees, not the main conversation tree.
		let changed = true;
		while (changed) {
			changed = false;
			for (const entry of this.fileEntries) {
				if (entry.type === "session") continue;
				if (!keepIds.has(entry.id) && entry.parentId && keepIds.has(entry.parentId)) {
					// Check if parent chain reaches a subagent_run
					let isUnderSubagent = subagentRunIds.has(entry.parentId);
					if (!isUnderSubagent) {
						let currentId: string | null | undefined = entry.parentId;
						while (currentId && keepIds.has(currentId)) {
							if (subagentRunIds.has(currentId)) {
								isUnderSubagent = true;
								break;
							}
							const parent = this.byId.get(currentId);
							currentId = parent?.parentId;
						}
					}
					if (isUnderSubagent) {
						keepIds.add(entry.id);
						changed = true;
					}
				}
			}
		}

		// Collect label entries whose targetId is in the keep set
		for (const entry of this.fileEntries) {
			if (entry.type === "label") {
				const labelEntry = entry as LabelEntry;
				if (keepIds.has(labelEntry.targetId)) {
					keepIds.add(entry.id);
				}
			}
		}

		// Remove orphaned entries
		const removedIds = new Set<string>();
		const header = this.fileEntries.find((e) => e.type === "session");
		this.fileEntries = this.fileEntries.filter((entry) => {
			if (entry.type === "session") return true;
			if (keepIds.has(entry.id)) return true;
			removedIds.add(entry.id);
			return false;
		});

		if (removedIds.size > 0) {
			this._buildIndex();
			if (header) {
				this._rewriteFile();
			}
		}

		return removedIds;
	}

	/**
	 * Apply data updates to multiple custom entries, then rewrite the session file once.
	 * Used by snapshot migration to rewrite legacy in-tree snapshot anchors to { refId }.
	 * @returns the number of entries actually updated.
	 */
	updateCustomEntriesData(updates: { entryId: string; data: unknown }[]): number {
		if (updates.length === 0) return 0;
		const updateMap = new Map<string, unknown>();
		for (const u of updates) updateMap.set(u.entryId, u.data);
		let changed = false;
		for (const entry of this.fileEntries) {
			if (entry.type === "custom" && updateMap.has(entry.id)) {
				(entry as CustomEntry).data = updateMap.get(entry.id);
				changed = true;
			}
		}
		if (changed) {
			const header = this.fileEntries.find((e) => e.type === "session");
			if (header) {
				this._rewriteFile();
			}
		}
		return updateMap.size;
	}

	/**
	 * Create a new session file containing only the path from root to the specified leaf.
	 * Useful for extracting a single conversation path from a branched session.
	 * Returns the new session file path, or undefined if not persisting.
	 */
	createBranchedSession(leafId: string): string | undefined {
		const previousSessionFile = this.sessionFile;
		const path = this.getBranch(leafId);
		if (path.length === 0) {
			throw new Error(`Entry ${leafId} not found`);
		}

		// Filter out LabelEntry from path - we'll recreate them from the resolved map
		const pathWithoutLabels = path.filter((e) => e.type !== "label");

		const newSessionId = createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(this.getSessionDir(), `${fileTimestamp}_${newSessionId}.jsonl`);

		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: this.persist ? previousSessionFile : undefined,
		};

		// Collect labels for entries in the path
		const pathEntryIds = new Set(pathWithoutLabels.map((e) => e.id));
		const labelsToWrite: Array<{ targetId: string; label: string; timestamp: string }> = [];
		for (const [targetId, label] of this.labelsById) {
			if (pathEntryIds.has(targetId)) {
				labelsToWrite.push({ targetId, label, timestamp: this.labelTimestampsById.get(targetId)! });
			}
		}

		if (this.persist) {
			// Build label entries
			const lastEntryId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
			let parentId = lastEntryId;
			const labelEntries: LabelEntry[] = [];
			for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
				const labelEntry: LabelEntry = {
					type: "label",
					id: generateId(new Set(pathEntryIds)),
					parentId,
					timestamp: labelTimestamp,
					targetId,
					label,
				};
				pathEntryIds.add(labelEntry.id);
				labelEntries.push(labelEntry);
				parentId = labelEntry.id;
			}

			this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
			this.sessionId = newSessionId;
			this._buildIndex();

			// lazy 条目的 offset 指向旧文件：在切换到新 sessionFile 前必须 materialize，
			// 否则新文件全量写入（_rewriteFile / _persist !flushed）会写占位丢内容。
			for (const e of this.fileEntries) {
				if (isLazyEntry(e)) {
					this.materialize(e.id);
				}
			}
			this.sessionFile = newSessionFile;

			// Only write the file now if it contains an assistant message.
			// Otherwise defer to _persist(), which creates the file on the
			// first assistant response, matching the newSession() contract
			// and avoiding the duplicate-header bug when _persist()'s
			// no-assistant guard later resets flushed to false.
			const hasAssistant = this.fileEntries.some((e) => e.type === "message" && e.message?.role === "assistant");
			if (hasAssistant) {
				this._rewriteFile();
				this.flushed = true;
			} else {
				this.flushed = false;
			}

			return newSessionFile;
		}

		// In-memory mode: replace current session with the path + labels
		const labelEntries: LabelEntry[] = [];
		let parentId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
		for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
			const labelEntry: LabelEntry = {
				type: "label",
				id: generateId(new Set([...pathEntryIds, ...labelEntries.map((e) => e.id)])),
				parentId,
				timestamp: labelTimestamp,
				targetId,
				label,
			};
			labelEntries.push(labelEntry);
			parentId = labelEntry.id;
		}
		this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
		this.sessionId = newSessionId;
		this._buildIndex();
		return undefined;
	}

	/**
	 * Create a new session.
	 * @param cwd Working directory (stored in session header)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 */
	static create(cwd: string, sessionDir?: string, options?: NewSessionOptions): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		return new SessionManager(cwd, dir, undefined, true, options);
	}

	/**
	 * Open a specific session file.
	 * @param path Path to session file
	 * @param sessionDir Optional session directory for /new or /branch. If omitted, derives from file's parent.
	 * @param cwdOverride Optional cwd override instead of the session header cwd.
	 */
	static open(path: string, sessionDir?: string, cwdOverride?: string): SessionManager {
		const resolvedPath = resolvePath(path);
		// Extract cwd from session header if possible, otherwise use process.cwd()
		const entries = loadEntriesFromFile(resolvedPath);
		const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
		const cwd = cwdOverride ?? header?.cwd ?? process.cwd();
		// If no sessionDir provided, derive from file's parent directory
		const dir = sessionDir ? normalizePath(sessionDir) : resolve(resolvedPath, "..");
		return new SessionManager(cwd, dir, resolvedPath, true, undefined, entries);
	}

	/** Create a SessionManager with a specific file path. */
	static createWithFile(
		cwd: string,
		sessionFile: string,
		sessionDir: string,
		options?: NewSessionOptions,
	): SessionManager {
		return new SessionManager(cwd, sessionDir, sessionFile, true, options);
	}

	/**
	 * Continue the most recent session, or create new if none.
	 * @param cwd Working directory
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 */
	static continueRecent(cwd: string, sessionDir?: string): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const mostRecent = findMostRecentSession(dir, filterCwd ? cwd : undefined);
		if (mostRecent) {
			return new SessionManager(cwd, dir, mostRecent, true);
		}
		return new SessionManager(cwd, dir, undefined, true);
	}

	/** Create an in-memory session (no file persistence) */
	static inMemory(cwd: string = process.cwd(), options?: NewSessionOptions): SessionManager {
		return new SessionManager(cwd, "", undefined, false, options);
	}

	/**
	 * Fork a session from another project directory into the current project.
	 * Creates a new session in the target cwd with the full history from the source session.
	 * @param sourcePath Path to the source session file
	 * @param targetCwd Target working directory (where the new session will be stored)
	 * @param sessionDir Optional session directory. If omitted, uses default for targetCwd.
	 */
	static forkFrom(
		sourcePath: string,
		targetCwd: string,
		sessionDir?: string,
		options?: NewSessionOptions,
	): SessionManager {
		const resolvedSourcePath = resolvePath(sourcePath);
		const resolvedTargetCwd = resolvePath(targetCwd);
		const sourceEntries = loadEntriesFromFile(resolvedSourcePath);
		if (sourceEntries.length === 0) {
			throw new Error(`Cannot fork: source session file is empty or invalid: ${resolvedSourcePath}`);
		}

		const sourceHeader = sourceEntries.find((e) => e.type === "session") as SessionHeader | undefined;
		if (!sourceHeader) {
			throw new Error(`Cannot fork: source session has no header: ${resolvedSourcePath}`);
		}

		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(resolvedTargetCwd);
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		// Create new session file with new ID but forked content
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		const newSessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(dir, `${fileTimestamp}_${newSessionId}.jsonl`);

		// Write new header pointing to source as parent, with updated cwd
		const newHeader: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: resolvedTargetCwd,
			parentSession: resolvedSourcePath,
		};
		writeFileSync(newSessionFile, `${JSON.stringify(newHeader)}\n`, { flag: "wx" });

		// Copy all non-header entries from source
		for (const entry of sourceEntries) {
			if (entry.type !== "session") {
				if (isLazyEntry(entry)) {
					// lazy 条目：从源文件 offset 读 raw 原样 append（避免 JSON.stringify 写占位）
					appendFileSync(newSessionFile, `${readRawLine(resolvedSourcePath, entry.offset, entry.length)}\n`);
				} else {
					appendFileSync(newSessionFile, `${JSON.stringify(entry)}\n`);
				}
			}
		}

		return new SessionManager(resolvedTargetCwd, dir, newSessionFile, true);
	}

	/**
	 * List all sessions for a directory.
	 * @param cwd Working directory (used to compute default session directory)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async list(cwd: string, sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]> {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const resolvedCwd = resolvePath(cwd);
		const sessions = (await listSessionsFromDir(dir, onProgress)).filter(
			(session) => !filterCwd || sessionCwdMatches(session.cwd, resolvedCwd),
		);
		sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
		return sessions;
	}

	/**
	 * List all sessions across all project directories.
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async listAll(onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(
		sessionDirOrOnProgress?: string | SessionListProgress,
		onProgress?: SessionListProgress,
	): Promise<SessionInfo[]> {
		const customSessionDir =
			typeof sessionDirOrOnProgress === "string" ? normalizePath(sessionDirOrOnProgress) : undefined;
		const progress = typeof sessionDirOrOnProgress === "function" ? sessionDirOrOnProgress : onProgress;
		if (customSessionDir) {
			const sessions = await listSessionsFromDir(customSessionDir, progress);
			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		}

		const sessionsDir = getSessionsDir();

		try {
			if (!existsSync(sessionsDir)) {
				return [];
			}
			const entries = await readdir(sessionsDir, { withFileTypes: true });
			const dirs = entries.filter((e) => e.isDirectory()).map((e) => join(sessionsDir, e.name));

			// Count total files first for accurate progress
			let totalFiles = 0;
			const dirFiles: string[][] = [];
			for (const dir of dirs) {
				try {
					const files = (await readdir(dir)).filter((f) => f.endsWith(".jsonl"));
					dirFiles.push(files.map((f) => join(dir, f)));
					totalFiles += files.length;
				} catch {
					dirFiles.push([]);
				}
			}

			// Process all files with progress tracking
			let loaded = 0;
			const sessions: SessionInfo[] = [];
			const allFiles = dirFiles.flat();

			const results = await buildSessionInfosWithConcurrency(allFiles, () => {
				loaded++;
				progress?.(loaded, totalFiles);
			});

			for (const info of results) {
				if (info) {
					sessions.push(info);
				}
			}

			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		} catch {
			return [];
		}
	}
}
